list: $/tecnotrade/mallextraadmin/models/mallagentimodel/columns.yaml
modelClass: Tecnotrade\Mallextraadmin\Models\MallAgentiModel
title: MallAgentiController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/mallextraadmin/mallagenticontroller/update/:id'
