plugin:
    name: 'tecnotrade.mallextraadmin::lang.plugin.name'
    description: 'tecnotrade.mallextraadmin::lang.plugin.description'
    author: Tecnotrade
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: 'Gestione Agenti'
        url: /
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: Agenti
                url: tecnotrade/mallextraadmin/mallagenticontroller
                icon: icon-table
